package com.chaiok.pos.domain.model

data class Arcus2NewWaySettings(
    val saleClass: String = "1",
    val saleOp: String = "1",
    val universalReversalClass: String = "1",
    val universalReversalOp: String = "5",
    val refundClass: String = "1",
    val refundOp: String = "11",
    val settlementClass: String = "2",
    val settlementOp: String = "1",
    val pingClass: String = "9",
    val pingOp: String = "6",
    val currencyRubCode: String = "643",
    val currencyAmdCode: String = "051",
    val sendPrintCommands: Boolean = true,
    val sendStartEndPrint: Boolean = true,
    val sendSetTags: Boolean = true,
    val sendStatusMessages: Boolean = true,
    val waitOkTimeoutMs: Long = 5000L,
    val maxReceiptPrintBlockBytes: Int = 500,
    val enableRawArcus2Log: Boolean = true,
    val declinedDefaultRc: String = "05",
    val cancelledRc: String = "999",
    val errorRc: String = "999",
    val minimalResultMode: Boolean = true,
    val waitOkAfterEachCommand: Boolean = false,
    val sendReceiptInMinimalMode: Boolean = true,
    val usePrintSessionMarkersInMinimalMode: Boolean = false,
    val drainOkAfterCommandMs: Long = 200L,
    val sendBeginTrOnPaymentStart: Boolean = true,
    val sendStatusOnPaymentStart: Boolean = true,
    val paymentStartStatusText: String = "Ожидание карты",
    val paymentStatusKeepAliveEnabled: Boolean = true,
    val cancelStatusKeepAliveEnabled: Boolean = false,
    val paymentStatusKeepAliveIntervalMs: Long = 5_000L,
    val cardWaitingStatusText: String = "Ожидание карты",
    val cardDetectedStatusText: String = "Карта считана",
    val processingStatusText: String = "Обработка",
    val pinRequiredStatusText: String = "Введите PIN",
    val cancellingStatusText: String = "Отмена",
    val additionalDataRequestEnabled: Boolean = true,
    val additionalDataRequestCommand: String = "GETTAGS:",
    val additionalDataReadTimeoutMs: Long = 1_000L,
    val additionalDataTotalTimeoutMs: Long = 8_000L,
    val additionalDataMaxFrames: Int = 8,
    val additionalDataGetTagsResponseMode: String = "IGNORE_AND_WAIT_TAGS",
    val sendStatusOnCancelStart: Boolean = false,
    val saleAdditionalDataEnabled: Boolean = false,
    val reversalAdditionalDataEnabled: Boolean = true,
    val refundAdditionalDataEnabled: Boolean = false,
    val settlementAdditionalDataEnabled: Boolean = false,
    val rrnTagKeysCsv: String = "rrn,r",
    val amountTagKeysCsv: String = "amount,a",
    val currencyTagKeysCsv: String = "currency,c",
    val orderIdTagKeysCsv: String = "orderId,order_id,order",
    val receiptNumberTagKeysCsv: String = "receiptNumber,receipt,cheque,check",
    val authCodeTagKeysCsv: String = "authCode,auth,approvalCode",
    val rrnOwTagIdsCsv: String = "1F8431,1F03",
    val amountOwTagIdsCsv: String = "9F02",
    val currencyOwTagIdsCsv: String = "5F2A",
    val terminalIdOwTagIdsCsv: String = "9F1C",
    val responseCodeOwTagIdsCsv: String = "1F0D"
)

data class AppSettings(
    val integrationModeEnabled: Boolean,
    val tableModeEnabled: Boolean,
    val tileBackground: String = "default",
    val pcUsbModeEnabled: Boolean = false,
    val pcIdleImages: List<String> = emptyList(),
    val pcCompactServiceFeeEnabled: Boolean = true,
    val showCustomTipButton: Boolean = true,
    val pcCompactPaymentDesignStyle: PcCompactPaymentDesignStyle = PcCompactPaymentDesignStyle.DEFAULT,
    val pcEcrProtocol: PcEcrProtocol = PcEcrProtocol.CHAIOK_JSON,
    val arcus2NewWaySettings: Arcus2NewWaySettings = Arcus2NewWaySettings()
)
